main.name = "GIVE_ME_A_NAME"
main.lang = "en"
main.whitelist = [
  "YOUR_WIFI_NAME_GOES_HERE",
]

main.plugins.grid.enabled = true
main.plugins.grid.report = true
main.plugins.grid.exclude = [
  "YOUR_WIFI_NAME_GOES_HERE"
]

ui.display.enabled = true
ui.display.type = "waveshare_3"
ui.display.color = "black"

bettercap.handshake = "/home/pi/handshakes"

