main.name = "GIVE_ME_A_NAME"
main.lang = "en"
main.whitelist = [
  "YOUR_WIFI_NAME_GOES_HERE",
]

main.plugins.grid.enabled = true
main.plugins.grid.report = true
main.plugins.grid.exclude = [
  "YOUR_WIFI_NAME_GOES_HERE"
]

ui.display.enabled = true
ui.display.type = "waveshare_3"
ui.display.color = "black"

bettercap.handshake = "/home/pi/handshakes"

#This config.toml file is a basic configuration that has been slightly modified. You just need to download it and make minor edits to get started quickly.
#Anything in all CAPS needs editing. Leave everything else as is.
